### ISSUE TITLE
Issues with MariaDB caused by constraint violation exceptions

### ISSUE THREAD

**Issue by WiIIiam278** [WiIIiam278/HuskSync#40]
Certain MariaDB environments cause an exception to occur when setting players or data into the database, only on MariaDB environments, probably due to missing user data.
```
[06:07:14 ERROR]: [HuskSync] Failed to set user data in the database
java.sql.SQLIntegrityConstraintViolationException: Cannot add or update a child row: a foreign key constraint fails (`s1_main`.`husksync_user_data`, CONSTRAINT `husksync_user_data_ibfk_1` FOREIGN KEY (`player_uuid`) REFERENCES `husksync_users` (`uuid`) ON DELETE CASCADE)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:117) ~[mysql-connector-java-8.0.27.jar:8.0.27]
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-java-8.0.27.jar:8.0.27]
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953) ~[mysql-connector-java-8.0.27.jar:8.0.27]
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1098) ~[mysql-connector-java-8.0.27.jar:8.0.27]
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1046) ~[mysql-connector-java-8.0.27.jar:8.0.27]
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1371) ~[mysql-connector-java-8.0.27.jar:8.0.27]
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:1031) ~[mysql-connector-java-8.0.27.jar:8.0.27]
        at net.william278.husksync.libraries.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61) ~[HuskSync-2.0.jar:?]
        at net.william278.husksync.libraries.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java) ~[HuskSync-2.0.jar:?]
        at net.william278.husksync.database.MySqlDatabase.lambda$setUserData$12(MySqlDatabase.java:364) ~[HuskSync-2.0.jar:?]
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
```

**Comment by gp-Airee** [comment]
Confirmed working on `10.8.3-MariaDB-1:10.8.3+maria~jammy` - from Docker Hub (`mariadb:latest`)

**Comment by Tiippex** [comment]
Hey,

does this only occur in version 2, or is version 1 also affected?

I am currently using 10.3.31-MariaDB with HuskSync version 1. I have not noticed any problems in this direction.

Should I wait to upgrade to v2?

Regards
Max

**Comment by WiIIiam278** [comment]
> Hey,
> 
> does this only occur in version 2, or is version 1 also affected?
> 
> I am currently using 10.3.31-MariaDB with HuskSync version 1. I have not noticed any problems in this direction.
> 
> Should I wait with an upgrade to v2?
> 
> Regards Max

Hi Max,

As far as I am aware, v1.x is not affected.
Duly note I no longer support v1.

Regards

**Comment by Tiippex** [comment]
Thanks for the fast reply!

> Duly note I no longer support v1.
Mhh, At the moment I use a galera cluster.
I would not like to convert that into a MySQL cluster setup.

Is there a chance that a fix will be available soon
Is there anything we can do to help?

Regards
Max

**Comment by WiIIiam278** [comment]
> Thanks for the fast reply!
> 
> > Duly note I no longer support v1.
> 
> Mhh, At the moment I use a galera cluster. I would not like to convert that into a MySQL cluster setup.
> 
> Is there a chance that a fix will be available soon Is there anything we can do to help?
> 
> Regards Max

Hey -

This issue is a tough one, unfortunately, and despite best efforts to reproduce it's been difficult to try and do so -- particularly as it seems to only occur on certain database implementations of Maria.

It's essentially caused by user data records either not having been created or invalid records being created for whatever reason when data saving needs to occur.

The best thing you can do to try and help is see if this issue affects your environment -- if you are able to spin up a server and try it on your environment and report back, that might help narrow things down.

Thanks

**Comment by Tiippex** [comment]
Hey,

I did some tests, but I was not able to reproduce the issue so far.

I have tried it with my Galera cluster as well as with an extra server and a single MariaDB instance.
For all tests, I used Debian 10 and 10.3.31-MariaDB

To force saving, I used the save-all command. Does that make a difference?
![image](https://user-images.githubusercontent.com/16509128/182713055-e0b96965-8f39-491e-8880-d858d99c1144.png)

**Comment by HarvelsX** [comment]
Probably fixed by adding a driver from MariaDB

**Comment by WiIIiam278** [comment]
Caused by a race condition imposed by a bug in #ensureUser. Specifically affects MariaDB due to different timings between MySQL and MDB, though can also affect MySQL. Fixed by correcting the asynchronous future logic in #ensureUser

**Comment by WiIIiam278** [comment]
Although this issue seems to occur significantly _less_, I have seen at least one or two reports of it persisting -- so I'm reopening this for further investigation.

**Comment by WiIIiam278** [comment]
Haven't seen any further reports or issues with this since last comment -- Closing for now.

**Comment by LuluxClient** [comment]
> Haven't seen any further reports or issues with this since last comment -- Closing for now.

Hey the issue is still persistant: https://pastebin.com/9GssV3tX

**Comment by WiIIiam278** [comment]
Moving this to issue #63 so this can be better understood. The key (pun unintended) thing is, this doesn't cause any in-game issues, just a console exception.
