### ISSUE TITLE
Locked Maps Loses Data after Server Restarts

### ISSUE THREAD

**Issue by MoNoLidThZ** [WiIIiam278/HuskSync#498]
### Plugin Version:
HuskSync version 3.8.1-404f18d

### Minecraft Version:
Paper version 1.21.4-226-ver/1.21.4@a838a88 (2025-04-17T19:20:57Z) (Implementing API version 1.21.4-R0.1-SNAPSHOT)

### Server Environment:
- Velocity-based proxy network
- HuskSync with MySQL&Redis backend
- Inventory sync enabled across multiple backend servers

### Description:
When a locked map is transferred from one server to another using HuskSync, it displays correctly on the receiving server until that server is restarted. Upon restarting, the map appears blank. This suggests that the map data is not being properly persisted to the world's map data files in the destination server.

### Steps to Reproduce:
1. Spawn a locked map in Server 1 using a known `map_x.dat` identifier.
2. Transfer the map to Server 2 via inventory sync (e.g., switching via `/server`).
3. Place the map in Server 2 (e.g., in an item frame or chest).
4. Restart Server 2.
5. Observe that the map is now blank upon rejoining Server 2.

### Expected Behavior:
The locked map should retain its visual data and render correctly after a server restart, regardless of which server it originated from.

### Actual Behavior:
After a restart, the map appears as an uninitialized or empty map. It no longer displays the expected content, despite appearing correctly when first transferred and placed.

#### Attachment 1: Bug on 2nd Server after Restarts
![Image](https://github.com/user-attachments/assets/d80ad9a8-66a9-4e6f-ba59-468ea6b99063)
#### Attachment 2: Expected Behavior
![Image](https://github.com/user-attachments/assets/f7f7f194-8487-45be-8b22-d21b2b1f8f01)

### Possible Cause:
Map data is not being persisted to the destination server's `data/map_x.dat` files during the HuskSync deserialization process. While the item metadata is preserved, the corresponding world data is not written, causing the client to lose visual reference upon world reload.

### Suggested Improvement:
Consider implementing support to ensure that map data is written to disk on the destination server when deserializing locked maps. This may require detection of map-type items and ensuring their associated data files exist within the destination world's data directory.

### Notes:
This issue may primarily affect creative or survival servers that utilize map art, exploration maps, or administrative locked maps as visual signage.

**Comment by siulung201314** [comment]
I have enable the debug mode.
And the debug log shows that
the plugin cannot find any data of pixel related to the locked maps from the database.
I have checked the database and ensure that the data of pixel is saved before.
I guess that plugin is trying to look for incorrect data (wrong original backend server with correct map id or correct original backend server with wrong map id).
Hope that this opinion may help to find the cause of the issue.

**Comment by WiIIiam278** [comment]
After some pretty thorough debugging, I think this is an unintended consequence of https://github.com/PaperMC/Paper/pull/12296 being merged.

For most Paper users, persisting virtual maps isn't needed / desired and causes lag on world save... For me, I need this as a feature (although I don't want to cause lag on world save of course, so...).

**Comment by WiIIiam278** [comment]
I had a chat with the Paper team to gather a bit more understanding about the function and limitations of the map APIs and determined the original strategy wasn't working as intended.

I have implemented a fix for this issue which will be included in the next release. Please test this and let me know.

**Comment by WiIIiam278** [comment]
The first error is expected.
The second is probably that this might not work with stuff before this update.

**Comment by MoNoLidThZ** [comment]
I've Tried the last commit (HuskSync-Bukkit-3.8.4-7ebf91b+mc.1.21.4) with Paper version 1.21.4-232-ver/1.21.4@12d8fe0 (2025-06-09T10:15:42Z) (Implementing API version 1.21.4-R0.1-SNAPSHOT)
and here's console error upon loading chunks with synced maps (it still shows empty)
```
[03:36:32 WARN]: net.william278.husksync.libraries.nbtapi.NbtApiException: [?][2.15.1-SNAPSHOT]Method not loaded! 'GET_SERIALIZATION_CONTEXT'
[03:36:32 WARN]: 	at HuskSync-Bukkit-3.8.4-7ebf91b+mc.1.21.4.jar//net.william278.husksync.libraries.nbtapi.utils.nmsmappings.ReflectionMethod.run(ReflectionMethod.java:408)
[03:36:32 WARN]: 	at HuskSync-Bukkit-3.8.4-7ebf91b+mc.1.21.4.jar//net.william278.husksync.libraries.nbtapi.NBTReflectionUtil.<clinit>(NBTReflectionUtil.java:80)
[03:36:32 WARN]: 	at HuskSync-Bukkit-3.8.4-7ebf91b+mc.1.21.4.jar//net.william278.husksync.libraries.nbtapi.NBTCompound.hasTag(NBTCompound.java:730)
[03:36:32 WARN]: 	at HuskSync-Bukkit-3.8.4-7ebf91b+mc.1.21.4.jar//net.william278.husksync.data.BukkitSerializer$Inventory.deserialize(BukkitSerializer.java:75)
[03:36:32 WARN]: 	at HuskSync-Bukkit-3.8.4-7ebf91b+mc.1.21.4.jar//net.william278.husksync.data.BukkitSerializer$Inventory.deserialize(BukkitSerializer.java:64)
[03:36:32 WARN]: 	at HuskSync-Bukkit-3.8.4-7ebf91b+mc.1.21.4.jar//net.william278.husksync.data.SerializerRegistry.lambda$deserializeData$6(SerializerRegistry.java:133)
[03:36:32 WARN]: 	at java.base/java.util.Optional.map(Optional.java:260)
[03:36:32 WARN]: 	at HuskSync-Bukkit-3.8.4-7ebf91b+mc.1.21.4.jar//net.william278.husksync.data.SerializerRegistry.deserializeData(SerializerRegistry.java:133)
[03:36:32 WARN]: 	at HuskSync-Bukkit-3.8.4-7ebf91b+mc.1.21.4.jar//net.william278.husksync.data.DataSnapshot$Unpacked.lambda$deserializeData$2(DataSnapshot.java:398)
[03:36:32 WARN]: 	at java.base/java.util.stream.Collectors.lambda$toMap$68(Collectors.java:1637)
[03:36:32 WARN]: 	at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
[03:36:32 WARN]: 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
[03:36:32 WARN]: 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
[03:36:32 WARN]: 	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
[03:36:32 WARN]: 	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1939)
[03:36:32 WARN]: 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
[03:36:32 WARN]: 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[03:36:32 WARN]: 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
[03:36:32 WARN]: 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[03:36:32 WARN]: 	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
[03:36:32 WARN]: 	at HuskSync-Bukkit-3.8.4-7ebf91b+mc.1.21.4.jar//net.william278.husksync.data.DataSnapshot$Unpacked.deserializeData(DataSnapshot.java:396)
[03:36:32 WARN]: 	at HuskSync-Bukkit-3.8.4-7ebf91b+mc.1.21.4.jar//net.william278.husksync.data.DataSnapshot$Unpacked.<init>(DataSnapshot.java:380)
[03:36:32 WARN]: 	at HuskSync-Bukkit-3.8.4-7ebf91b+mc.1.21.4.jar//net.william278.husksync.data.DataSnapshot$Packed.unpack(DataSnapshot.java:359)
[03:36:32 WARN]: 	at HuskSync-Bukkit-3.8.4-7ebf91b+mc.1.21.4.jar//net.william278.husksync.hook.PlanHook$PlanDataExtension.lambda$getLatestSnapshot$1(PlanHook.java:127)
[03:36:32 WARN]: 	at java.base/java.util.Optional.map(Optional.java:260)
[03:36:32 WARN]: 	at HuskSync-Bukkit-3.8.4-7ebf91b+mc.1.21.4.jar//net.william278.husksync.hook.PlanHook$PlanDataExtension.getLatestSnapshot(PlanHook.java:127)
[03:36:32 WARN]: 	at HuskSync-Bukkit-3.8.4-7ebf91b+mc.1.21.4.jar//net.william278.husksync.hook.PlanHook$PlanDataExtension.getUserHasSynced(PlanHook.java:140)
[03:36:32 WARN]: 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[03:36:32 WARN]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[03:36:32 WARN]: 	at Plan-5.6-build-2965.jar//com.djrapitops.plan.extension.implementation.providers.Parameters$PlayerParameters.usingOn(Parameters.java:97)
[03:36:32 WARN]: 	at Plan-5.6-build-2965.jar//com.djrapitops.plan.extension.implementation.providers.MethodWrapper.callMethod(MethodWrapper.java:50)
[03:36:32 WARN]: 	at Plan-5.6-build-2965.jar//com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.callMethod(DataValueGatherer.java:322)
[03:36:32 WARN]: 	at Plan-5.6-build-2965.jar//com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.lambda$tryToBuildBoolean$7(DataValueGatherer.java:301)
[03:36:32 WARN]: 	at Plan-5.6-build-2965.jar//com.djrapitops.plan.extension.implementation.builder.BuiltDataValue.getValue(BuiltDataValue.java:48)
[03:36:32 WARN]: 	at Plan-5.6-build-2965.jar//com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.getValue(DataValueGatherer.java:452)
[03:36:32 WARN]: 	at Plan-5.6-build-2965.jar//com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.storePlayerBoolean(DataValueGatherer.java:541)
[03:36:32 WARN]: 	at Plan-5.6-build-2965.jar//com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.lambda$gatherPlayer$9(DataValueGatherer.java:372)
[03:36:32 WARN]: 	at java.base/java.util.Optional.ifPresent(Optional.java:178)
[03:36:32 WARN]: 	at Plan-5.6-build-2965.jar//com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.gatherPlayer(DataValueGatherer.java:372)
[03:36:32 WARN]: 	at Plan-5.6-build-2965.jar//com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.tryToUpdateValues(DataValueGatherer.java:344)
[03:36:32 WARN]: 	at Plan-5.6-build-2965.jar//com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.updateValues(DataValueGatherer.java:331)
[03:36:32 WARN]: 	at Plan-5.6-build-2965.jar//com.djrapitops.plan.extension.ExtensionSvc.updatePlayerValues(ExtensionSvc.java:181)
[03:36:32 WARN]: 	at Plan-5.6-build-2965.jar//com.djrapitops.plan.extension.ExtensionSvc.updatePlayerValues(ExtensionSvc.java:165)
[03:36:32 WARN]: 	at Plan-5.6-build-2965.jar//com.djrapitops.plan.gathering.events.PlayerJoinEventConsumer.lambda$updatePlayerDataExtensionValues$10(PlayerJoinEventConsumer.java:205)
[03:36:32 WARN]: 	at Plan-5.6-build-2965.jar//com.djrapitops.plan.processing.Processing.lambda$submitNonCritical$1(Processing.java:85)
[03:36:32 WARN]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[03:36:32 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[03:36:32 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[03:36:32 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)```

**Comment by MoNoLidThZ** [comment]
> I used the latest commit([7ebf91b](https://github.com/WiIIiam278/HuskSync/commit/7ebf91bfae2695880600ae1fab2ec89117461e16)) for testing and found that it seems the player must have this locked map painting in their inventory and join the server in order for the locked map painting in the item_frame to display correctly after the server restarts. For example, when a player who has the map painting in their inventory does not join this server, the locked map painting in the item_frame will not display. However, as long as the player with the map painting in their inventory joins the server, the locked map painting in the item_frame will load and display.

I can confirm the reproducibility of this, so the current workaround is to have player pull the maps out of the wall, switch to original server and join back and then their maps are loaded correctly

The potential (but painful) solution can be another redis key which remembers a list of map ids to load data on server and apply it but however we cannot be sure if the chunk or entity is loaded

**Comment by WiIIiam278** [comment]
Try with latest commit again

**Comment by waiching514** [comment]
I have identified issues with the map painting function following a server restart:

Map Paintings Not Displaying Properly: Players need to place the map painting in their inventory and relog to restore its display.

Locked Map Paintings Showing Incorrect Content: Some locked map paintings may still display incorrect content or fail to load properly.

**Comment by WiIIiam278** [comment]
Yep, the system isn't perfect with maps in an item frame yet.
